FROM scratch
LABEL maintainer "notogawa <n.ohkawa@idein.jp>"

ADD rootfs.tar.xz  /

ENV LC_ALL=C.UTF-8
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LD_LIBRARY_PATH=/opt/vc/lib:${LD_LIBRARY_PATH}
ENV DEBIAN_FRONTEND=noninteractive

# update ca certificates
RUN update-ca-certificates --fresh

WORKDIR /root
STOPSIGNAL SIGTERM
CMD ["/bin/bash"]
